FROM node:14

WORKDIR /app

COPY package*.json ./

RUN npm install --save --legacy-peer-deps
RUN npm install @mui/material @mui/icons-material

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
