FROM node:14 AS build
WORKDIR /app
COPY package*.json ./
RUN npm cache clean --force
RUN npm install react-scripts --save --legacy-peer-deps
RUN npm install --save --legacy-peer-deps
COPY . .
RUN npm run build

FROM node:14
WORKDIR /app
COPY --from=build /app /app
EXPOSE 3000
CMD ["npm", "start"]
