FROM node:14

WORKDIR /app

COPY . .

WORKDIR ./
RUN npm install --save --legacy-peer-deps
RUN npm install @mui/material @mui/icons-material

RUN npm run build

EXPOSE 4000

WORKDIR /app/src/server
CMD ["node", "crawlingserver.js"]
