version: '3'
services:
  frontend:
    image: penguingong/project
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"

  backend:
    image: penguingong/project
    build:
      context: ./
      dockerfile: Dockerfile-backend
    ports:
      - "3002:3002"

  backend2:
    image: penguingong/project
    build:
      context: ./
      dockerfile: Dockerfile-backend2
    ports:
      - "4000:4000"
