version: '3'
services:
  frontend:
    container_name: docker-frontend
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"

  backend:
    container_name: docker-backend
    build:
      context: ./
      dockerfile: Dockerfile-backend
    ports:
      - "3002:3002"

  backend2:
    container_name: docker-backend2
    build:
      context: ./
      dockerfile: Dockerfile-backend2
    ports:
      - "4000:4000"
